# Run with julia --project=slides/lectures/Lecture_2A/notebooks this_file.jl
ENV["GKSwstype"]="100"
using Random, Statistics, Distributions, Plots, JSON
include(joinpath(@__DIR__,"TreeLab.jl"))
using .TreeLab
figdir=joinpath(@__DIR__,"..","figures");mkpath(figdir)
widgetdir=joinpath(@__DIR__,"..","widgets");mkpath(widgetdir)
train=sample_data(180,21);val=sample_data(360,22)
trees=[fit_tree(train.X,train.y;depth=d,minleaf=2) for d in 1:10]
bag=forest(train.X,train.y;ntrees=30,depth=6)
boost=fit_boost(train.X,train.y;rounds=20)
score(t,data)=accuracy([predict_tree(t,x) for x in eachrow(data.X)],data.y)
signal=rand(MersenneTwister(42),Beta(2,5),1000)
background=rand(MersenneTwister(43),Beta(5,2),1000)
metrics=Dict("train"=>[score(t,train) for t in trees],"validation"=>[score(t,val) for t in trees])
data=Dict("train"=>Dict("X"=>[collect(x) for x in eachrow(train.X)],"y"=>train.y),"validation"=>Dict("X"=>[collect(x) for x in eachrow(val.X)],"y"=>val.y),"trees"=>trees,"bag"=>bag,"boost"=>boost,"metrics"=>metrics,"signal"=>signal,"background"=>background)
open(joinpath(widgetdir,"data.js"),"w") do io
    write(io,"// Generated by notebooks/export_material.jl; seeds 21,22,42,43.\nwindow.LECTURE_DATA = ")
    JSON.print(io,data);write(io,";\n")
end
theme(:boxed; fontfamily="Helvetica",guidefontsize=17,tickfontsize=13,legendfontsize=13,titlefontsize=19,linewidth=3,background_color=:white,grid=false,size=(1100,700))
g=range(0,1;length=101)
function boundary(t,name,title)
    p=heatmap(g,g,[predict_tree(t,[x,y]) for y in g,x in g];c=cgrad(["#d9e5ef","#ffe4a3"]),clims=(-1,1),colorbar=false,xlabel="feature 1",ylabel="feature 2",title,aspect_ratio=1)
    for label in (-1,1)
        ids=train.y .== label
        scatter!(p,train.X[ids,1],train.X[ids,2];color=label==1 ? "#d99700" : "#253b53",markersize=7,markerstrokewidth=0,label=label==1 ? "signal" : "background")
    end
    savefig(p,joinpath(figdir,name))
end
boundary(trees[3],"tree-depth-3.svg","Depth 3")
boundary(trees[10],"tree-depth-10.svg","Depth 10")
p=plot(1:10,metrics["train"];label="training",xlabel="maximum depth",ylabel="accuracy",ylims=(0.5,1.02),marker=:circle,markersize=8,markerstrokewidth=0)
plot!(p,1:10,metrics["validation"];label="validation",marker=:circle,markersize=8,markerstrokewidth=0)
savefig(p,joinpath(figdir,"depth-accuracy.svg"))
p=plot(g,[impurity(x) for x in g];label="Gini: p(1-p)",xlabel="signal fraction p",ylabel="impurity")
plot!(p,g,[impurity(x,:entropy) for x in g];label="entropy (natural log)")
savefig(p,joinpath(figdir,"impurity.svg"))

# Exact fitted depth-5 tree with features, cuts, gains, and leaf statistics.
depth5=fit_tree(train.X,train.y;depth=5,minleaf=2)
dotpath=joinpath(figdir,"tree-depth-5.dot")
open(dotpath,"w") do io
    println(io,"digraph Tree {")
    println(io,"graph [rankdir=TB, bgcolor=\"transparent\", nodesep=0.13, ranksep=0.24, pad=0.05];")
    println(io,"node [shape=box, style=\"rounded,filled\", fontname=\"Helvetica\", fontsize=14, margin=\"0.08,0.04\", color=\"#087bb9\", penwidth=1.6];")
    println(io,"edge [fontname=\"Helvetica\", fontsize=11, color=\"#58778c\", arrowsize=0.55];")
    nextid=Ref(0)
    function emit(t)
        nextid[]+=1; id=nextid[]
        if haskey(t,"feature")
            feature=t["feature"]; cut=round(t["cut"],digits=3)
            gain=round(t["gain"],digits=4); count=t["n"]
            label="x$feature < $cut\\nΔI=$gain · n=$count"
            println(io,"n$id [label=\"$label\", fillcolor=\"#e9f5fd\"];")
            left=emit(t["left"]); right=emit(t["right"])
            println(io,"n$id -> n$left [label=\"yes\"];")
            println(io,"n$id -> n$right [label=\"no\"];")
        else
            cls=t["value"]==1 ? "signal" : "background"
            color=t["value"]==1 ? "#ffe4a3" : "#d9e5ef"
            probability=round(t["p"],digits=2); count=t["n"]
            label="$cls\\np=$probability · n=$count"
            println(io,"n$id [label=\"$label\", fillcolor=\"$color\", color=\"#8b99a3\"];")
        end
        id
    end
    emit(depth5)
    println(io,"}")
end
run(`dot -Tsvg $dotpath -o $(joinpath(figdir,"tree-depth-5.svg"))`)
open(joinpath(figdir,"results.json"),"w") do io
    JSON.print(io,metrics,2)
end
println("Exported data and four Julia figures. Depth 3: ",metrics["train"][3]," / ",metrics["validation"][3])
